menu:
  list:
    title: "Coupon List"
    items:
      fill:
        material: GRAY_STAINED_GLASS_PANE
        amount: 1
        name: "&f"
      close:
        material: BARRIER
        amount: 1
        name: "&cClose menu"
        lore:
          - '&f'
          - ' &f- &7Left Click to close menu'
      information:
        material: PAPER
        amount: 1
        name: "&6Information"
        lore:
          - '&f'
          - ' &f&aCoupons: &2%coupons_amount%'
      coupon:
        material: MAP
        amount: 1
        name: "&9%coupon_name%"
        lore:
          - '&f'
          - ' &f&aMoney: &2%coupon_money%'
          - ' &f&aXP: &2%coupon_xp%'
          - ' &f&aItems: &2%coupon_items%'
          - ' &f&aMessages: &2%coupon_messages%'
          - ' &f&aCommands: &2%coupon_commands%'
          - ' &f&aPermission: &2%coupon_permission%'
          - ' &f&aMax uses: &2%coupon_max_uses%'
          - '&f'
          - ' &f- &7Left Click to get coupon'
          - ' &f- &7Right Click to edit coupon'
      next-page:
        material: ARROW
        amount: 1
        name: "&6Next page"
      previous-page:
        material: ARROW
        amount: 1
        name: "&6Previous page"
        lore:
          - '&f'
          - ' &f- &7Left Click to g'
  edit:
    title: "Editing coupon"
    items:
      close:
        material: BARRIER
        amount: 1
        name: "&cClose"
        lore:
          - "&f"
          - " &f- &7Left Click to close menu"
      delete:
        material: REDSTONE_BLOCK
        amount: 1
        name: "&4Delete Coupon"
        lore:
          - "&f"
          - " &f- &7Left Click to delete coupon"
      money:
        material: GOLD_INGOT
        amount: 1
        name: "&6Change money reward"
        lore:
          - "&f"
          - " &f&aActual reward: &2%coupon_money%"
          - "&f"
          - " &f- &7Left Click to change amount"
      xp:
        material: EXPERIENCE_BOTTLE
        amount: 1
        name: "&6Change XP reward"
        lore:
          - "&f"
          - " &f&aActual reward: &2%coupon_xp%"
          - "&f"
          - " &f- &7Left Click to change amount"
      items:
        material: CHEST
        amount: 1
        name: "&6Change item rewards"
        lore:
          - "&f"
          - " &f&aActual amount: &2%coupon_items%"
          - "&f"
          - " &f- &7Left Click to change items"
      messages:
        material: PAPER
        amount: 1
        name: "&6Change reward messages"
        lore:
          - "&f"
          - " &f&aActual amount: &2%coupon_messages%"
          - "&f"
          - " &f- &7Left Click to add message"
          - " &f- &7Right Click to change position"
      commands:
        material: COMMAND_BLOCK
        amount: 1
        name: "&6Change reward commands"
        lore:
          - "&f"
          - " &f&aActual amount: &2%coupon_commands%"
          - "&f"
          - " &f- &7Left Click to add command"
          - " &f- &7Right Click to change position"
      permission:
        material: NAME_TAG
        amount: 1
        name: "&6Change coupon permission"
        lore:
          - "&f"
          - " &f&aActual permission: &2%coupon_permission%"
          - "&f"
          - " &f- &7Left Click to change permission"
      max-uses:
        material: BOOK
        amount: 1
        name: "&6Change coupon max uses"
        lore:
          - "&f"
          - " &f&aActual max uses: &2%coupon_max_uses%"
          - "&f"
          - " &f- &7Left Click to change max uses"

  items:
    title: "Put all item rewards"
  texts-menu:
    title: "Editing &o%path%"
    items:
      messages:
        material: PAPER
        amount: 1
        name: "&6%message%"
        lore:
          - "&f"
          - " &f- &7Left Click move to left"
          - " &f- &7Middle Click to delete"
          - " &f- &7Right Click move to right"
      commands:
        material: COMMAND_BLOCK
        amount: 1
        name: "&6%command%"
        lore:
          - "&f"
          - " &f- &7Left Click move to left"
          - " &f- &7Middle Click to delete"
          - " &f- &7Right Click move to right"
  delete:
    title: "Delete coupon?"
    items:
      coupon:
        material: MAP
        amount: 1
        name: "&9%coupon_name%"
        lore:
          - '&f'
          - ' &f&aMoney: &2%coupon_money%'
          - ' &f&aXP: &2%coupon_xp%'
          - ' &f&aItems: &2%coupon_items%'
          - ' &f&aMessages: &2%coupon_messages%'
          - ' &f&aCommands: &2%coupon_commands%'
      confirm:
        material: GREEN_WOOL
        amount: 1
        name: "&aDelete Coupon"
        lore:
          - "&f"
          - " &f- &7Left Click to confirm"
      cancel:
        material: RED_WOOL
        amount: 1
        name: "&cCancel"
        lore:
          - "&f"
          - " &f- &7Left Click to cancel"