name: SimpleCoupons
main: org.kayteam.simplecoupons.SimpleCoupons
version: 1.3
authors: [segu23, SirOswaldo]
website: https://kayteam.org
softdepend: [Vault, PlaceholderAPI]
api-version: 1.13
commands:
  simplecoupons:
    aliases: [sc]
permissions:
  simplecoupons.admin:
    children:
      - simplecoupons.create
      - simplecoupons.delete
      - simplecoupons.edit
      - simplecoupons.get
      - simplecoupons.give
      - simplecoupons.help
      - simplecoupons.list
      - simplecoupons.reload
